#!/bin/bash

PATH=/usr/bin:/home/pi/wiringPi/gpio

echo "ATXRaspi shutdown script starting..."
echo "Asserting pins (24=in,low; 23=out,high)"

gpio -g mode 24 in
gpio -g write 24 0
gpio -g mode 23 out
gpio -g write 23 1

COUNTER=0

#while [ $COUNTER -lt 10 ]; do
while [ 1 ]; do
    #echo Looping - counter is $COUNTER
    #let COUNTER=COUNTER+1
    #sleep 1
    if [ "$(/home/pi/wiringPi/gpio/gpio -g read 24)" = "1" ]; then
        echo "PIN24 requested a SYSTEM HALT !"
        touch /home/pi/pitunes/halting
        sudo halt
  break
    fi
    sudo sleep 0.5
done


exit 0